# specify version of yaml syntax
version: "3"

services:
  django-app: # service name to run the docker file
    build:
      context: . # use current directory that running the docker-compose command
      args:
        - DEV=false
    ports:
      - "8000:8000"
    volumes:
      - ./django-project:/django-project
    command:
    >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             python3 cpserver.py"
    environment:
      - POSTGRES_HOST=db # use database connection as define in below db service
      - POSTGRES_DB=db_100
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=Password_dev_sdfl23pp234_3w342asdf
    depends_on:
      - db

  db:
    image: postgres:15.5-bookworm # use postgres 15.5 on Debian 12
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_100
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=Password_dev_sdfl23pp234_3w342asdf
      - TZ=Asia/Vientiane # set default env time zone to UTC +7
      - PGTZ=Asia/Vientiane # set postgres time zone to UTC +7
      - POSTGRES_HOST_AUTH_METHOD=trust # allow to connect to db from all hosts

volumes:
  db-data:
