version: "3.9"

services:
  django-app:
    build:
        context: . # use current directory that running the docker-compose command
        args:
          - DEV=false
    container_name: django-app
    #env_file: .env  # Load environment variables from .env
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres # Use the service name as the hostname
      - POSTGRES_USER=db_user_100
      - POSTGRES_PASSWORD=db_password_100_example!!!
      - POSTGRES_DB=db_name_100
      # - SECRET_KEY=django_secret_key
    volumes:
      - ./django-project:/django-project # Mount/sync django-project directory on host with django-project on docker
    networks:  # Add this to connect to the database network
      - internal-network
    command:
    >
        sh -c "python3 manage.py wait_for_db && \
               python3 manage.py makemigrations && \
               python3 manage.py migrate && \
               python3 manage.py collectstatic --noinput && \
               python3 cpserver.py"
