# specify version of yaml syntax
version: "3"

services:
  django-app: # service name to run the docker file
    build:
      context: . # use current directory that running the docker-compose command
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./django-project:/django-project
    command:
    >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_HOST=db # use database connection as define in below db service
      - POSTGRES_DB=db_100
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=Password_dev_sdfl23pp234_3w342asdf
