# docker-compose.yml (Main file)
version: "3.9"

volumes:
  postgres_data:  # Define persitant the volume
  pgadmin_data:

networks:
  internal-network:  # Define the network

services:
  postgres:
    extends:
      file: docker-compose.db.yml
      service: postgres

  memcached:
    extends:
      file: docker-compose.memcached.yml
      service: memcached

  pgadmin:
    extends:
      file: docker-compose.pgadmin.yml
      service: pgadmin
    depends_on:
      - postgres

  django-app:
    extends:
      file: docker-compose.django.yml
      service: django-app
    depends_on:
      - postgres
      - memcached
