version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4:latest  # Use the latest pgAdmin image
    container_name: pgadmin
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin_email@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password_example!!!
    volumes:
      - pgAdmin_data:/var/lib/pgadmin4
    restart: always # Restart pgAdmin if it crashes

volumes:
  pgAdmin_data:
