# Generated by Django 5.1.5 on 2025-02-06 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 8 digits.', regex='^\\d{8}$')]),
        ),
    ]
